### ISSUE TITLE
If you click on Connect before clicking on Login the game crashed instantly

### ISSUE THREAD

**Issue by Fireztonez** [blakdragan7/vscci#5]
I just installed the 0.0.3 verison on my game, open a world, enter the command `.vscci config` to open the interface and I saw my twitch account is not connected anymore, so I click on Connect and after that I click on Login because it show "Disconnected". When I click on that button, the webpage open and the game crash instantly.

I tried that twice and the game crashed twice with the same message. After that I tried the other way and the mod connect just fine to Twitch, so I think you should add a little verification to avoid that crash.

Crash report: https://gist.github.com/Fireztonez/4c3ecfcec9e89e771ed8f24cbe2854da

**Comment by blakdragan7** [comment]
uh, I totally can't read that because I can only read english lol

**Comment by blakdragan7** [comment]
but I can fix anyway.

**Comment by blakdragan7** [comment]
fixed as of c7bc85d085a1892d190438450c988659955ddbd5 because it is no longer possible to do this.
