### ISSUE TITLE
[Suggestion] Twitch connection should be automatic, when you have already connected once

### ISSUE THREAD

**Issue by Fireztonez** [blakdragan7/vscci#6]
Presently, once you already have login on Twitch once, when you open the world again and open the VSCCI Config GUI, you can see you Username and Twicth ID, but you still have to click on Connect question to connect to the Twitch account. I think it would be nice if this was automatic.

I think once you're connected to your account once, everithing should work directly when you open your game. If a connection problem appends you should just send a private chat message I think to warn the streamer about the issue.

Other little thing, I think it will be nice, if you can change the connect button for a disconnect button, question to give agility to simply disconnect the account.

** By the way, I try to find the file where you save the Twitch information and I can't find it anywhere, is it saved in an accessible file?

**Comment by blakdragan7** [comment]
yes it's saved as vscci_data.json in the CWD of the program. I am not sure where that will be though. But it should be the same place you found the config last time. 

Also yes, totally makes sense for it to auto login and make it a disconnect button instead of connect. Will 100% do that

**Comment by blakdragan7** [comment]
Done via c7bc85d085a1892d190438450c988659955ddbd5
